### ISSUE TITLE
No status_table entry for 10: Shutdown

### ISSUE THREAD

**Issue by mhughes2k** [airnotifier/airnotifier#112]
This may not be related to a log entry we saw where suddenly Airnotifer generated
(The empty line is one i added to dump the value of data out)

```
[W 150721 18:13:41 apns:167] strathuni_test[0] is offline 1
[E 150721 18:13:41 apns:206] response must be a 6-byte binary string.
[E 150721 18:13:41 apns:207]
[E 150721 18:13:41 iostream:319] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 316, in wrapper
        callback(*args)
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 241, in wrapped
        callback(*args, **kwargs)
      File "/usr/local/airnotifier/pushservices/apns.py", line 209, in _on_remote_read_close
        (command, statuscode, identifier) = struct.unpack_from('!bbI', data, 0)
    error: unpack_from requires a buffer of at least 6 bytes
[E 150721 18:13:41 ioloop:467] Exception in callback <functools.partial object at 0x7fef64682e10>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 453, in _run_callback
        callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 241, in wrapped
        callback(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 316, in wrapper
        callback(*args)
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 241, in wrapped
        callback(*args, **kwargs)
      File "/usr/local/airnotifier/pushservices/apns.py", line 209, in _on_remote_read_close
        (command, statuscode, identifier) = struct.unpack_from('!bbI', data, 0)
    error: unpack_from requires a buffer of at least 6 bytes
```

The Apple Docs (https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html) has a status not covered in the _on_remote_read_close() function's status_table construct for a status code of 10, indicating a shutdown.

**Comment by dcai** [comment]
Thanks @mhughes2k it seems that package should be ignored instead of being processed by airnotifier.

**Comment by mhughes2k** [comment]
I raised this question on the commit:

>Doesn't this change mean that if a socket is closed, with a non-6 byte binary string, then the stream is still left open but self.connected is now reporting that it is not connected?
>Also the APNS docs says that in the case of a "10" response the stream should be dropped and re-connected, and that doesn't look it happens
>(I'm not normally a python developer, so I'm hoping I've read this right...but let me know if I haven't)

Also I found 
>An occasional disconnect while your provider is idle is nothing to be concerned about; just re-establish the connection and carry on. If one of the push servers is down, the load balancing mechanism will transparently direct your new connection to another server assuming you connect by hostname and not by static IP address.
which appears to be happening to us an Airnotifier *isn't* re-establishing the connection.
