### ISSUE TITLE
Crash -> MemoryError

### ISSUE THREAD

**Issue by MartinSchultz** [airnotifier/airnotifier#161]
Recently I began to see often weird crashes with AirNotifier - see the log here:

[I 161019 16:09:38 web:1908] 200 POST /api/v2/tokens (xx.xxx.xxx.xxx) 3.72ms
Traceback (most recent call last):
  File "/var/www/project/airnotifier_live/airnotifier.py", line 285, in <module>
    AirNotifierApp(services=services).main()
  File "/var/www/project/airnotifier_live/airnotifier.py", line 204, in main
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
MemoryError

Any idea what could have caused this?

Thanks
Martin

**Comment by MartinSchultz** [comment]
Found the reason. It was a low memory condition on the server. I moved the push service to an own server and don't see any issues anymore.
