### ISSUE TITLE
/api/v2/tokens return MissingArgumentError: HTTP 400: Bad Request (Missing argument appname)

### ISSUE THREAD

**Issue by takishi** [airnotifier/airnotifier#171]
Hi friends,
please i'm looking for help to slove this problem:
http://X.X.X.X:8801/api/v2/tokens, return:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/root/airnotifier/api/__init__.py", line 82, in prepare
    self.appname = filter_alphabetanum(self.get_argument('appname'))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 385, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 462, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument appname)

best regards.
samuel.

**Comment by takishi** [comment]
hi friends, 
some one can hellp me here!?

best regards.
samuel.

**Comment by vitaly-safonov** [comment]
@takishi  I have the same problem, are you fix it?
