### ISSUE TITLE
Apple p8 key throws error

### ISSUE THREAD

**Issue by Dranick** [airnotifier/airnotifier#183]
I have exported the Apple .p8 key, uploaded the certificate and the key but upon starting the server I get the following error:

`    [E 180411 18:22:03 ioloop:612] Exception in callback None
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
        handler_func(fd_obj, events)
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 504, in _handle_events
        self._handle_connect()
      File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 1359, in _handle_connect
        do_handshake_on_connect=False)
      File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 501, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 478, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    SSLError: [SSL: NO_CERTIFICATE_ASSIGNED] no certificate assigned (_ssl.c:2726)
[W 180411 18:22:03 apns:225] XXX[0] is offline. Reconnected?: 1
[E 180411 18:22:03 apns:255] 0 byte recieved.
[E 180411 18:22:03 apns:259] Attempting re-connect...`

Please help.

Thank you!

**Comment by dcai** [comment]
please use Certificate-Based Provider-to-APNs Trust, token based auth isn't implemented yet.
